### ISSUE TITLE
User commands should override rules command

### ISSUE THREAD

**Issue by gmarty** [fxbox/thinkerbell#28]
The user command should have the priority over rules in case of conflicts.

Case 1
A rule says 'turn on the lights between 6pm and 7pm'.
If a user turns off the lights on 6:30pm, then the lights must not be switched back on by the engine.

Case 2
A rule says 'turn on the lights when the motion sensor detects activity'.
A user can turn off the lights after the motion sensor turned it on. The sensor will still turn on the lights after that.

**Comment by Yoric** [comment]
Marking as closed, because that's already how it works, without specific coding. Let's reopen if we find out I'm wrong or if the default behavior changes.
