### ISSUE TITLE
Move the simulator into the main code

### ISSUE THREAD

**Issue by Yoric** [fxbox/thinkerbell#35]
Currently, the simulator lives in `examples/`. This means that:
- it is not run by `cargo test`;
- it cannot be used by tests;
- it cannot be used by FoxBox.

We should move the code of the simulator into its module of `src/` and use it to write tests.

Once this transformation is complete, `examples/simulator.rs` should pretty much be reduced to its current `fn main()`.

**Comment by JohanLorenzo** [comment]
Working on it :)
