### ISSUE TITLE
The rule manager should store the User

### ISSUE THREAD

**Issue by Yoric** [fxbox/thinkerbell#65]
Calls to fetch, send and watch now require a `User`, which may be useful e.g. for WebPush. For the moment, Thinkerbell does not propagate the User, so we cannot use WebPush from a recipe. To fix this, we should store the User whenever we insert a recipe – and propagate this to the Thinkerbell adapter.

@mcav, do you have time to handle this?

cc @ferjm and @aosmond , our local WebPush/User experts.

**Comment by ferjm** [comment]
I'm interested on digging into Thinkerbell's internals, so I'd like to give this a try if you don't mind.

**Comment by Yoric** [comment]
Sounds good.

The database is managed [here](https://github.com/fxbox/thinkerbell/blob/master/src/manager.rs) and the adapter [here](https://github.com/fxbox/foxbox/blob/master/src/adapters/thinkerbell/mod.rs).

**Comment by Yoric** [comment]
This has been fixed a while ago.
