### ISSUE TITLE
Recipe should not be saved if there is an error during compilation of its script

### ISSUE THREAD

**Issue by azasypkin** [fxbox/thinkerbell#79]
We have an issue right now: when we create recipe and its source has problems (like mismatch of Range and ChannelKind) - the recipe is still created, but without source.

**Comment by Yoric** [comment]
When you say that the recipe is created, are you looking at the database file?

**Comment by azasypkin** [comment]
@Yoric Mm, no I just see that it's returned in the list of services with the following selector ```{ getters: [{ kind: 'ThinkerbellRuleSource' }] }```

**Comment by Yoric** [comment]
Ok, I think I found the issue.
